spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ucaretreatmentsystem@gmail.com
spring.mail.password=kxyb plmz qnaz wlbi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=dawb74ee9
cloudinary.api_key=475893293928147
cloudinary.api_secret=FL7FOuDnOnKDApdr_0KGMGPuz2M
